config/routes.rb
Rails.application.routes.draw do
  resources :chats, only: [:show, :create]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get "/home/about"=>"homes#about", as: "about"
  get "/search" => "searches#search", as: "search"
  post "/search" => "searches#search_data", as: "search_data"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence:true
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.book_id = book.id
    if comment.save
      @post_comment = comment
      @book = Book.find(params[:book_id])
    else
      @post_comment = comment
      render :error
    end
    # redirect_to request.referer
  end

  def destroy
    PostComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    @book = Book.find(params[:book_id])
  # redirect_to request.referer
  end

  private
  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/views/post_comments/_form.html.erb
<%= form_with model:[book, post_comment], local: false do |f| %>
  <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに", class: "w-100" %>
  <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
<% end %>

app/views/post_comments/_index.html.erb
<table>
  <tbody>
      <% book.post_comments.each do |post_comment| %>
      <tr>

        <td>
          <%= link_to user_path(post_comment.user) do %>
            <%= image_tag post_comment.user.get_profile_image(100,100) %><br>
            <%= post_comment.user.name %>
          <% end %>
        </td>
        <td><%= post_comment.comment %></td>
        <td>
          <% if post_comment.user == current_user %>
            <%= link_to "Destroy", book_post_comment_path(book, post_comment), method: :delete, remote: true, class: "btn btn-danger pull-right" %>
          <% end %>
        </td>
      </tr>
      <% end %>
  </tbody>
</table>

app/views/post_comments/create.js.erb
$(".comments_count-<%= @book.id %>").html("コメント数: <%= @book.post_comments.count %>");
$(".post_comments").html("<%= escape_javascript(render partial: "post_comments/index", locals: {book: @book}) %>");
$("#post_comment_comment").val("");

app/views/post_comments/destroy.js.erb
$(".comments_count-<%= @book.id %>").html("コメント数: <%= @book.post_comments.count %>");
$(".post_comments").html("<%= escape_javascript(render partial: "post_comments/index", locals: {book: @book}) %>");
$("#post_comment_comment").val("");

app/views/post_comments/error.js.erb
$("main > .container").prepend("<%= j(render"layouts/errors", obj: @post_comment) %>");